---
# Sistema installato: SDDM con la sessione ZETA RAYS (anche per l'accesso automatico).
displaymanagers:
  - sddm
defaultDesktopEnvironment:
    executable: "zeta-desktop-session"
    desktopFile: "zeta"
basicSetup: false
sysconfigSetup: false
