#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Builds Firefox's start page from the website (sito-zetarays/).

Firefox's homepage (policies.json) is file:///usr/share/zetarays/start/index.html:
  - online  -> the page checks that zetarays.org really answers and moves on to
               the live site (https://zetarays.org/);
  - offline -> it stays on this local copy of the site: same look and text,
               no external resources, and every link switched off, so Firefox
               never shows its network error page.
Run by build.sh before every build, so the copy always matches the website.

  genera-pagina-firefox.py <site dir> <output dir>
"""
import os
import re
import shutil
import sys

ONLINE_URL = "https://zetarays.org/"
PROBE_URL = "https://zetarays.org/"
PROBE_TIMEOUT_MS = 2500

HEAD_EXTRA = """
<!-- ZETA RAYS: local copy of zetarays.org used as Firefox's start page.
     Generated by tools/genera-pagina-firefox.py, do not edit by hand. -->
<style>
  /* offline copy: links are text, not destinations */
  a, a:hover { cursor: default !important; }
  a { pointer-events: none !important; }
  /* small label in the corner: it must never cover the page */
  .zr-offline-note {
    position: fixed; right: 12px; bottom: 12px; max-width: calc(100%% - 24px);
    z-index: 9999; padding: 5px 10px; border-radius: 999px; margin: 0;
    background: rgba(15, 15, 18, 0.88); border: 1px solid rgba(237, 237, 234, 0.10);
    color: #8a8a90; font: 500 10.5px/1.2 "JetBrains Mono", ui-monospace, monospace;
    letter-spacing: 0.03em; white-space: nowrap; pointer-events: none;
  }
</style>
<script>
// Online: go to the live site, but only after checking that it really answers
// (a network cable or Wi-Fi alone is not enough). Offline: stay here.
(function () {
  "use strict";
  var ONLINE_URL = %(online)s, PROBE_URL = %(probe)s, TIMEOUT = %(timeout)d;
  if (!navigator.onLine || !window.fetch || !window.AbortController) return;
  var ctl = new AbortController();
  var timer = setTimeout(function () { ctl.abort(); }, TIMEOUT);
  // HEAD request: only the headers travel, and any answer (even an error
  // code) proves the site is reachable
  fetch(PROBE_URL, { method: "HEAD", mode: "no-cors", cache: "no-store",
        credentials: "omit", signal: ctl.signal })
    .then(function () { clearTimeout(timer); location.replace(ONLINE_URL); })
    .catch(function () { clearTimeout(timer); });
})();
</script>
"""

BODY_EXTRA = """
<p class="zr-offline-note" id="zr-offline-note"></p>
<script>
// Keep every link inert, including the ones the language switch re-creates.
(function () {
  "use strict";
  // the note follows the page language (IT/EN switch of the site)
  var nota = document.getElementById("zr-offline-note");
  function testo() {
    nota.textContent = document.documentElement.lang === "it"
      ? "Copia offline di zetarays.org \u00b7 link disattivati"
      : "Offline copy of zetarays.org \u00b7 links are disabled";
  }
  testo();
  new MutationObserver(testo).observe(document.documentElement, { attributes: true, attributeFilter: ["lang"] });
  function spegni(root) {
    (root.querySelectorAll ? root.querySelectorAll("a[href]") : []).forEach(function (a) {
      a.removeAttribute("href"); a.removeAttribute("target");
      a.setAttribute("aria-disabled", "true");
    });
  }
  spegni(document);
  new MutationObserver(function (list) {
    list.forEach(function (m) { m.addedNodes.forEach(function (n) {
      if (n.nodeType === 1) { if (n.tagName === "A") spegni(n.parentNode); else spegni(n); }
    }); });
  }).observe(document.body, { childList: true, subtree: true });
  document.addEventListener("click", function (e) {
    if (e.target.closest && e.target.closest("a")) e.preventDefault();
  }, true);
})();
</script>
"""


def main(site, out):
    page = open(os.path.join(site, "index.html"), encoding="utf-8").read()

    # no external resources: Google Fonts out (JetBrains Mono is installed)
    page = re.sub(r'\s*<link[^>]+(?:fonts\.googleapis\.com|fonts\.gstatic\.com)[^>]*>', "", page)
    page = re.sub(r'\s*<link rel="canonical"[^>]*>', "", page)
    # links off: plain anchors and the ones stored for the language switch
    page = re.sub(r'(<a\b[^>]*?)\s+href="[^"]*"', r"\1", page)
    page = re.sub(r'(<a\b[^>]*?)\s+target="[^"]*"', r"\1", page)
    page = re.sub(r'\s+href=&quot;[^&]*&quot;', "", page)
    page = re.sub(r'\s+target=&quot;[^&]*&quot;', "", page)

    extra = HEAD_EXTRA % {"online": '"%s"' % ONLINE_URL, "probe": '"%s"' % PROBE_URL,
                          "timeout": PROBE_TIMEOUT_MS}
    # the site writes no <head>/<body> tags (HTML5 allows it): the head part
    # goes right after </title>, the body part at the very end
    assert page.count("</title>") == 1
    page = page.replace("</title>", "</title>" + extra, 1)
    if page.count("</html>") == 1:
        page = page.replace("</html>", BODY_EXTRA + "</html>", 1)
    else:
        page = page.rstrip() + "\n" + BODY_EXTRA

    # nothing left that would load from the network
    esterni = re.findall(r'(?:src|href)="(https?://[^"]+)"', page)
    if esterni:
        sys.exit("risorse esterne rimaste: %s" % esterni)

    if os.path.isdir(out):
        shutil.rmtree(out)
    os.makedirs(out)
    with open(os.path.join(out, "index.html"), "w", encoding="utf-8") as f:
        f.write(page)
    for nome in ("favicon.svg", "favicon-32.png", "apple-touch-icon.png"):
        if os.path.exists(os.path.join(site, nome)):
            shutil.copy2(os.path.join(site, nome), out)
    shutil.copytree(os.path.join(site, "fonts"), os.path.join(out, "fonts"))
    shutil.copytree(os.path.join(site, "sfondi", "miniature"),
                    os.path.join(out, "sfondi", "miniature"))
    print("pagina iniziale di Firefox: %s" % out)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2])
