#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""ZETA RAYS translations: extract, merge, check and compile (no dependencies).

    tools/i18n.py extract            write po/zetarays.pot from the code
    tools/i18n.py merge FILE.json..  add English->Italian pairs to po/it.po
    tools/i18n.py check              every string in the code has an Italian
                                     translation, no translation is stale,
                                     placeholders match (exit 1 otherwise)
    tools/i18n.py compile            po/*.po -> usr/share/locale/*/LC_MESSAGES/zetarays.mo

Python strings are marked with tr("..."), ntr("...", "...", n) and
trc("context", "...") (usr/lib/zeta/i18n.py); shell scripts use gettext "...",
ngettext "..." "..." N (and tq "..." in zeta-terminale) with
TEXTDOMAIN=zetarays. A msgid with a context is kept as "context\x04msgid",
the same key gettext uses in .mo files. The .mo files are generated by build.sh and are not
kept in the repository.
"""
import ast
import json
import os
import re
import struct
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CODE = os.path.join(ROOT, "live-build", "config", "includes.chroot")
PO_DIR = os.path.join(ROOT, "po")
POT = os.path.join(PO_DIR, "zetarays.pot")
DOMAIN = "zetarays"
SCRIPT_DIRS = ("usr/local/bin", "usr/libexec", "usr/local/libexec", "usr/lib/live/config",
               "etc/NetworkManager/dispatcher.d")
PLACEHOLDER = re.compile(r"\{[A-Za-z_][A-Za-z0-9_]*\}|%[sd]")


# ------------------------------------------------------------------ files
def _is_python(path):
    if path.endswith(".py"):
        return True
    try:
        with open(path, "rb") as f:
            head = f.read(40)
    except OSError:
        return False
    return head.startswith((b"#!/usr/bin/python3", b"#!/usr/bin/env python3"))


def _is_shell(path):
    try:
        with open(path, "rb") as f:
            head = f.read(40)
    except OSError:
        return False
    return head.startswith((b"#!/bin/sh", b"#!/bin/bash", b"#!/usr/bin/env bash", b"#!/usr/bin/bash"))


def code_files():
    py, sh = [], []
    for base, _dirs, files in os.walk(os.path.join(CODE, "usr", "lib", "zeta")):
        py += [os.path.join(base, f) for f in files if f.endswith(".py")]
    for d in SCRIPT_DIRS:
        full = os.path.join(CODE, d)
        if not os.path.isdir(full):
            continue
        for f in sorted(os.listdir(full)):
            p = os.path.join(full, f)
            if not os.path.isfile(p) or os.path.islink(p):
                continue
            if _is_python(p):
                py.append(p)
            elif _is_shell(p):
                sh.append(p)
    return sorted(set(py)), sorted(set(sh))


# ------------------------------------------------------------------ extract
def extract():
    """{msgid: {"plural": str|None, "refs": [file:line]}}"""
    found = {}
    errors = []
    py, sh = code_files()

    def add(msgid, plural, ref):
        e = found.setdefault(msgid, {"plural": plural, "refs": []})
        if plural and e["plural"] and e["plural"] != plural:
            errors.append("%s: same msgid with two plurals: %r" % (ref, msgid))
        e["plural"] = e["plural"] or plural
        e["refs"].append(ref)

    for path in py:
        rel = os.path.relpath(path, CODE)
        try:
            tree = ast.parse(open(path, encoding="utf-8").read(), path)
        except SyntaxError as e:
            errors.append("%s: syntax error: %s" % (rel, e))
            continue
        for node in ast.walk(tree):
            if not (isinstance(node, ast.Call) and isinstance(node.func, ast.Name)
                    and node.func.id in ("tr", "ntr", "trc")):
                continue
            ref = "%s:%d" % (rel, node.lineno)
            args = node.args
            want = {"tr": 1, "ntr": 3, "trc": 2}[node.func.id]
            if len(args) != want:
                errors.append("%s: %s() needs %d arguments" % (ref, node.func.id, want))
                continue
            lits = [a.value if isinstance(a, ast.Constant) and isinstance(a.value, str) else None
                    for a in args[:2 if want > 1 else 1]]
            if None in lits:
                errors.append("%s: %s() must receive string literals" % (ref, node.func.id))
                continue
            if node.func.id == "trc":
                add(lits[0] + "\x04" + lits[1], None, ref)
            else:
                add(lits[0], lits[1] if want == 3 else None, ref)

    lit = r"""(?:"((?:[^"\\]|\\.)*)"|'([^']*)')"""
    sh_call = re.compile(r"\b(?:gettext|tq)\s+(?:--\s+)?" + lit)
    sh_plural = re.compile(r"\bngettext\s+(?:--\s+)?" + lit + r"\s+" + lit)

    def sh_text(m, i):
        if m.group(i + 1) is not None:
            return m.group(i + 1)
        return re.sub(r'\\(["\\$`])', r"\1", m.group(i) or "")

    for path in sh:
        rel = os.path.relpath(path, CODE)
        testo = open(path, encoding="utf-8", errors="replace").read()
        # the whole file, not line by line: help texts span several lines
        inizio_riga = [0] + [k + 1 for k, c in enumerate(testo) if c == "\n"]

        def riga_di(pos):
            import bisect
            return bisect.bisect_right(inizio_riga, pos)

        def in_commento(pos):
            n = riga_di(pos) - 1
            return testo[inizio_riga[n]:pos].lstrip().startswith("#")

        plurali = []
        for m in sh_plural.finditer(testo):
            if not in_commento(m.start()):
                add(sh_text(m, 1), sh_text(m, 3), "%s:%d" % (rel, riga_di(m.start())))
                plurali.append((m.start(), m.end()))
        for m in sh_call.finditer(testo):
            if in_commento(m.start()) or any(a <= m.start() < b for a, b in plurali):
                continue
            text = sh_text(m, 1)
            # "$1" is the argument of a wrapper function, not a string
            if text and not text.startswith("-") and not re.fullmatch(r"\$\{?\w+\}?", text):
                add(text, None, "%s:%d" % (rel, riga_di(m.start())))
    return found, errors


# ------------------------------------------------------------------ po files
def _quote(s):
    s = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\t", "\\t")
    return '"%s"' % s


def _unquote(s):
    s = s.strip()
    assert s.startswith('"') and s.endswith('"'), s
    out, i, body = [], 0, s[1:-1]
    while i < len(body):
        c = body[i]
        if c == "\\" and i + 1 < len(body):
            n = body[i + 1]
            out.append({"n": "\n", "t": "\t", '"': '"', "\\": "\\"}.get(n, "\\" + n))
            i += 2
        else:
            out.append(c)
            i += 1
    return "".join(out)


def read_po(path):
    """{msgid: {"plural": str|None, "str": [str, ...]}} (header excluded)"""
    entries = {}
    if not os.path.exists(path):
        return entries
    cur, key = None, None

    def flush():
        if cur and cur.get("msgid"):
            key = cur["msgctxt"] + "\x04" + cur["msgid"] if cur.get("msgctxt") is not None else cur["msgid"]
            entries[key] = {"plural": cur.get("msgid_plural"),
                            "str": [cur["str"][k] for k in sorted(cur["str"])]}

    ctx = None

    for line in open(path, encoding="utf-8"):
        line = line.rstrip("\n")
        if not line.strip() or line.startswith("#"):
            continue
        mc = re.match(r'^msgctxt\s+(".*")$', line)
        if mc:
            flush()
            cur = None
            ctx = _unquote(mc.group(1))
            key = ("ctx", None)
            continue
        m = re.match(r'^(msgid|msgid_plural|msgstr(?:\[(\d+)\])?)\s+(".*")$', line)
        if m:
            if m.group(1) == "msgid":
                if cur is not None:
                    flush()
                cur = {"msgid": "", "str": {}, "msgctxt": ctx}
                ctx = None
            val = _unquote(m.group(3))
            if m.group(1) == "msgid":
                key = ("msgid", None)
                cur["msgid"] = val
            elif m.group(1) == "msgid_plural":
                key = ("msgid_plural", None)
                cur["msgid_plural"] = val
            else:
                idx = int(m.group(2) or 0)
                key = ("str", idx)
                cur["str"][idx] = val
        elif line.startswith('"') and key and key[0] == "ctx":
            ctx += _unquote(line)
        elif line.startswith('"') and cur is not None:
            val = _unquote(line)
            if key[0] == "str":
                cur["str"][key[1]] += val
            else:
                cur[key[0]] += val
    flush()
    return entries


HEADER_IT = (
    'msgid ""\nmsgstr ""\n'
    '"Project-Id-Version: ZETA RAYS OS\\n"\n'
    '"Language: it\\n"\n'
    '"MIME-Version: 1.0\\n"\n'
    '"Content-Type: text/plain; charset=UTF-8\\n"\n'
    '"Content-Transfer-Encoding: 8bit\\n"\n'
    '"Plural-Forms: nplurals=2; plural=(n != 1);\\n"\n')

HEADER_POT = HEADER_IT.replace('"Language: it\\n"\n', '"Language: \\n"\n')


def write_po(path, entries, header, refs=None):
    out = [header]
    for msgid in sorted(entries, key=lambda k: (refs or {}).get(k, [""])[0] + "\0" + k):
        e = entries[msgid]
        out.append("")
        for r in (refs or {}).get(msgid, [])[:4]:
            out.append("#: " + r)
        if "\x04" in msgid:
            ctx, plain = msgid.split("\x04", 1)
            out.append("msgctxt " + _quote(ctx))
        else:
            plain = msgid
        out.append("msgid " + _quote(plain))
        if e.get("plural"):
            out.append("msgid_plural " + _quote(e["plural"]))
            strs = e.get("str") or ["", ""]
            for i, s in enumerate(strs):
                out.append("msgstr[%d] %s" % (i, _quote(s)))
        else:
            out.append("msgstr " + _quote((e.get("str") or [""])[0]))
    with open(path + ".tmp", "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    os.replace(path + ".tmp", path)


# ------------------------------------------------------------------ commands
def cmd_extract():
    found, errors = extract()
    os.makedirs(PO_DIR, exist_ok=True)
    pot = {k: {"plural": v["plural"], "str": ["", ""] if v["plural"] else [""]} for k, v in found.items()}
    write_po(POT, pot, HEADER_POT, {k: v["refs"] for k, v in found.items()})
    for e in errors:
        print("ERROR:", e)
    print("%d strings extracted to %s" % (len(found), os.path.relpath(POT, ROOT)))
    return 1 if errors else 0


def cmd_merge(files):
    path = os.path.join(PO_DIR, "it.po")
    po = read_po(path)
    added = changed = 0
    for f in files:
        for e in json.load(open(f, encoding="utf-8")):
            if e.get("ctx") == "reference":
                continue                      # .desktop/polkit pairs: not gettext strings
            en, it = e["en"], e["it"]
            if e.get("context"):
                en = e["context"] + "\x04" + en
            entry = {"plural": e.get("plural_en"),
                     "str": [it, e.get("plural_it", it)] if e.get("plural_en") else [it]}
            if en in po and po[en] != entry:
                changed += 1
            elif en not in po:
                added += 1
            po[en] = entry
    found, _err = extract()
    stale = [k for k in po if k not in found]
    for k in stale:
        del po[k]                             # no longer in the code
    os.makedirs(PO_DIR, exist_ok=True)
    write_po(path, po, HEADER_IT, {k: v["refs"] for k, v in found.items()})
    print("it.po: %d added, %d changed, %d removed (stale), %d total" % (added, changed, len(stale), len(po)))
    return 0


def _placeholders(s):
    return sorted(PLACEHOLDER.findall(s.split("\x04", 1)[-1]))


def cmd_check():
    found, errors = extract()
    problems = list(errors)
    for name in sorted(os.listdir(PO_DIR)) if os.path.isdir(PO_DIR) else []:
        if not name.endswith(".po"):
            continue
        lang = name[:-3]
        po = read_po(os.path.join(PO_DIR, name))
        missing = [k for k in found if k not in po or not all(po[k]["str"])]
        stale = [k for k in po if k not in found]
        for k in missing:
            problems.append("%s: not translated: %r (%s)" % (lang, k, found[k]["refs"][0]))
        for k in stale:
            problems.append("%s: stale (no longer in the code): %r" % (lang, k))
        for k, e in po.items():
            if k not in found:
                continue
            for s in e["str"]:
                if s and _placeholders(s) != _placeholders(k) and not (e["plural"] and "{n}" not in s):
                    problems.append("%s: placeholders differ: %r -> %r" % (lang, k, s))
            if e["plural"] != found[k]["plural"]:
                problems.append("%s: plural form differs: %r" % (lang, k))
        print("%s: %d/%d translated" % (lang, len(found) - len(missing), len(found)))
    for p in problems:
        print("PROBLEM:", p)
    print("%d strings in the code, %d problems" % (len(found), len(problems)))
    return 1 if problems else 0


def write_mo(entries, path):
    """GNU .mo file (same layout msgfmt writes)."""
    items = {"": ("Content-Type: text/plain; charset=UTF-8\n"
                  "Plural-Forms: nplurals=2; plural=(n != 1);\n")}
    for msgid, e in entries.items():
        if not all(e["str"]):
            continue                       # untranslated: gettext falls back to English
        if e["plural"]:
            items[msgid + "\0" + e["plural"]] = "\0".join(e["str"])
        else:
            items[msgid] = e["str"][0]
    keys = sorted(items, key=lambda k: k.encode("utf-8"))
    ids = strs = b""
    offsets = []
    for k in keys:
        kb, vb = k.encode("utf-8"), items[k].encode("utf-8")
        offsets.append((len(ids), len(kb), len(strs), len(vb)))
        ids += kb + b"\0"
        strs += vb + b"\0"
    n = len(keys)
    keystart = 7 * 4 + 16 * n
    valuestart = keystart + len(ids)
    koffsets, voffsets = [], []
    for o1, l1, o2, l2 in offsets:
        koffsets += [l1, o1 + keystart]
        voffsets += [l2, o2 + valuestart]
    data = struct.pack("Iiiiiii", 0x950412de, 0, n, 7 * 4, 7 * 4 + n * 8, 0, 0)
    data += struct.pack("%di" % len(koffsets), *koffsets)
    data += struct.pack("%di" % len(voffsets), *voffsets)
    data += ids + strs
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path + ".tmp", "wb") as f:
        f.write(data)
    os.replace(path + ".tmp", path)
    return n - 1


def cmd_compile():
    for name in sorted(os.listdir(PO_DIR)):
        if not name.endswith(".po"):
            continue
        lang = name[:-3]
        dest = os.path.join(CODE, "usr", "share", "locale", lang, "LC_MESSAGES", DOMAIN + ".mo")
        n = write_mo(read_po(os.path.join(PO_DIR, name)), dest)
        print("%s: %d strings -> %s" % (lang, n, os.path.relpath(dest, ROOT)))
    return 0


def main(argv):
    if not argv:
        sys.exit(__doc__)
    cmd = argv[0]
    if cmd == "extract":
        return cmd_extract()
    if cmd == "merge":
        return cmd_merge(argv[1:])
    if cmd == "check":
        return cmd_check()
    if cmd == "compile":
        return cmd_compile()
    sys.exit(__doc__)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
