# ZETA RAYS — tema del terminale «contrasto»: Nero ad alto contrasto
# accento=FFFFFF
[cursor]
style=block
color=000000 @ACCENT@
[colors]
alpha=@ALPHA@
background=000000
foreground=FFFFFF
regular0=000000
regular1=FF5555
regular2=55FF55
regular3=FFFF55
regular4=5599FF
regular5=FF55FF
regular6=55FFFF
regular7=FFFFFF
bright0=AAAAAA
bright1=FF7777
bright2=77FF77
bright3=FFFF77
bright4=77AAFF
bright5=FF77FF
bright6=77FFFF
bright7=FFFFFF
selection-background=@SEL@
selection-foreground=FFFFFF
